name: example
description: An example project for dart_json_schema.
version: 2.5.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dart_json_schema_annotations:
    path: ../dart_json_schema_annotations
#    publish_to: ../dart_json_schema_annotations


dev_dependencies:
  build_runner: ^2.4.7
  dart_json_schema:
    path: ../

