name: dart_json_schema
description: A Dart/Flutter package that provides a simple @Field annotation for adding metadata to model fields and generates standard JSON schemas using a command-line tool.
version: 2.0.0
homepage: https://github.com/sagarmahobia/dart_json_schema

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^6.0.0
  path: ^1.8.0
  yaml: ^3.1.0
  args: ^2.4.0
  dart_json_schema_annotations:
    path: ./dart_json_schema_annotations
  build: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.21.0
  flutter_lints: ^3.0.0
  build_runner: ^2.3.0

executables:
  dart_json_schema: